name: Add Labels on Push
on: push
jobs:
  add-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: lannonbr/issue-label-manager-action@847b8a89ca581b97acbbe936e8521f74f11aa584
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
