name: Add Labels on Push
on: push
jobs:
  add-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: lannonbr/issue-label-manager-action@f3fc93accac8194c3c6a4a781dec5f852819df9b
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
