name: Add Labels on Push
on: push
jobs:
  add-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: lannonbr/issue-label-manager-action@27295bcfbcb0c5480e9ab0d3b4b08ce5cd9d3bb9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
